[theme]
primaryColor = "#1E90FF"  # Couleur principale (par exemple, pour les boutons)
backgroundColor = "#FFFFFF"  # Fond blanc
secondaryBackgroundColor = "#F0F2F6"  # Arrière-plan secondaire (widgets)
textColor = "#000000"  # Texte en noir
font = "sans serif"  # Choix de la police (sans serif, serif, monospace)